import EDITOR_TAB_SIZE from './editor';

const { VITE_SOCKET_URL, VITE_STUN_URL, VITE_TURN_URL, VITE_TURN_USERNAME, VITE_TURN_CREDENTIAL, VITE_API_URL } = import.meta.env;

export { VITE_SOCKET_URL, VITE_STUN_URL, VITE_TURN_URL, VITE_TURN_USERNAME, VITE_TURN_CREDENTIAL, EDITOR_TAB_SIZE, VITE_API_URL };
