const {
  VITE_SOCKET_URL,
  VITE_STUN_URL,
  VITE_TURN_URL,
  VITE_TURN_USERNAME,
  VITE_TURN_CREDENTIAL,
  VITE_API_URL,
  VITE_CHAT_URL,
  VITE_CODE_RUNNING_SOCKET_URL,
  MODE,
} = import.meta.env;

export {
  VITE_SOCKET_URL,
  VITE_STUN_URL,
  VITE_TURN_URL,
  VITE_TURN_USERNAME,
  VITE_TURN_CREDENTIAL,
  VITE_API_URL,
  VITE_CHAT_URL,
  VITE_CODE_RUNNING_SOCKET_URL,
  MODE,
};
